# Site settings
title: "Nya Feinstein"
description: "PhD Student | Data Scientist | Linguist"
url: "https://nyafein.github.io" # your GitHub Pages URL
baseurl: "" # leave empty if your site is at the root

# Theme
theme: jekyll-theme-cayman

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

# For later: Add sidebar 
#sidebar:
#  nav: ["About", "Education", "Research", "Projects", "Fun Facts", "Nya in the News", "Contact"]




#https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
